language: node_js

node_js:
 - "0.10"
 - "0.8"

before_install:
 - sudo apt-get -qq update

install:
 - npm install mocha
 - npm install aws-sdk

before_script:
 - npm install --build-from-source
 - npm test
 - node-pre-gyp package publish
 - node-pre-gyp clean

script:
 - make clean
 - sudo apt-get -qq install libzip-dev
 - npm install --build-from-source --shared_libzip
 - npm test
 # test installing from remote
 - make clean
 - npm install --fallback-to-build=false
 - npm test
 - node-pre-gyp clean

after_success:
# if success then query and display all published binaries
 - node-pre-gyp info

env:
  global:
   - secure: hBUfRqVPovL7PVOJONI8sakIUtggpM74qMPdi5zaMpJhuV/QWfROOVc05ULEr1P0Fra2WpQ62mp8lfa1NbB6sQfT/8Y6u0lucf9SsIUBJzDrSmfXv2NDgpJn9RQmfsZgLfDuTwRLVROkNSTowUq3tnhDIzX/NyB7uOp1TZNEJ8A=
   - secure: xWyq1Ys9lpMUVCh73q5YDDfC4nLeeydqIS4S+lJ/t/jUCNHDwe1x5XrxRIALi74qNmHg6eTcOeEW5iot/sf1oUJIA1oPt9iMIMolg9iYWJKWN4E6gWcIigYu9ZDl3GJsHyiNs/dVlZjzY1YKzyvgZ2MRfy4l0rPShCxROoCiCIM=
