language: node_js

node_js:
 - "0.10"
 - "0.8"

before_install:
 - sudo apt-get -qq update

install:
 - npm install mocha

before_script:
 - npm install --build-from-source
 - npm test

script:
 - make clean
 - sudo apt-get -qq install libzip-dev
 - npm install --build-from-source --shared_libzip
 - npm test
